### ISSUE TITLE
AddProperty fails if properties file is empty

### ISSUE THREAD

**Issue by fabiocarvalho777** [paypal/butterfly#111]
AddProperty operation fails if properties file is empty. The exception below is thrown. It fails when determining which EOL character to use.

The solution should be to use the OS default EOL character whenever the properties file is empty.

An unit test should be added to reproduce the bug and exercise this use case.

```
[10:09:17.544] [ERROR] SampleExtension:SampleTransformationTemplate-17-AddProperty has failed due to the exception below
com.paypal.butterfly.extensions.api.exception.TransformationUtilityException: Utility SampleExtension:SampleTransformationTemplate-17-AddProperty has failed
    at com.paypal.butterfly.extensions.api.TransformationUtility.perform(TransformationUtility.java:610)
    at com.paypal.butterfly.extensions.api.TransformationOperation.perform(TransformationOperation.java:86)
    at com.paypal.butterfly.core.TransformationEngine.perform(TransformationEngine.java:322)
    at com.paypal.butterfly.core.TransformationEngine.perform(TransformationEngine.java:191)
    at com.paypal.butterfly.core.TransformationEngine.perform(TransformationEngine.java:171)
    at com.paypal.butterfly.core.TransformationEngine.perform(TransformationEngine.java:126)
    at com.paypal.butterfly.core.TransformationEngine.perform(TransformationEngine.java:72)
    at com.paypal.butterfly.core.ButterflyFacadeImpl.transform(ButterflyFacadeImpl.java:125)
    at com.paypal.butterfly.core.ButterflyFacadeImpl.transform(ButterflyFacadeImpl.java:103)
    at com.paypal.butterfly.cli.ButterflyCliRunner.run(ButterflyCliRunner.java:163)
    at com.paypal.butterfly.cli.ButterflyCliApp.main(ButterflyCliApp.java:45)
Caused by: java.lang.IllegalArgumentException: Line argument cannot be null
    at com.paypal.butterfly.utilities.operations.EolHelper.getEndEol(EolHelper.java:143)
    at com.paypal.butterfly.utilities.operations.EolHelper.findEol(EolHelper.java:36)
    at com.paypal.butterfly.utilities.operations.EolHelper.findEolDefaultToOs(EolHelper.java:53)
    at com.paypal.butterfly.utilities.operations.properties.AddProperty.addProperty(AddProperty.java:131)
    at com.paypal.butterfly.utilities.operations.properties.AddProperty.execution(AddProperty.java:84)
    at com.paypal.butterfly.utilities.operations.properties.AddProperty.execution(AddProperty.java:23)
    at com.paypal.butterfly.extensions.api.TransformationUtility.perform(TransformationUtility.java:606)
    ... 10 common frames omitted
```

**Comment by amriteya** [comment]
Apologies for my limited understanding of the system.

This is what I understood about the issue. _AddProperty_ is a **TU** which fails when the properties file is empty i.e. when the first line of a property is appended to the file. 

From what I understand from the [code snippet](https://github.com/paypal/butterfly/blob/butterfly_3/butterfly-utilities/src/main/java/com/paypal/butterfly/utilities/operations/properties/AddProperty.java#L130-L131), the logic is to append an EOL character (presumably to the previous line of property) and then append the new property line.

If the above assumption is correct, when the property file is empty, the “EOL” character should be **empty string** as compared to OS default EOL character.
However, OS default EOL character is also acceptable as long as it is okay to have properties files starting with empty line.

@fabiocarvalho777 Thoughts?

**Comment by fabiocarvalho777** [comment]
@amriteya good point Amrit. I think you are right, in this case we should not even bother then adding a EOL, just add the property. Next time another attempt to add a property happens, the TO will add EOL first then the property, which will work fine too.

So yes, you are right.

ps.: a tip, write the unit test first, see it failing, then add the fix.

**Comment by amriteya** [comment]
Noted. Thanks for the tip Fabio.
