### ISSUE TITLE
Modify PomAddDependency to preserve file formatting and comments

### ISSUE THREAD

**Issue by fabiocarvalho777** [paypal/butterfly#92]

**Comment by badalsarkar** [comment]
Hi,
I have started working on it.

**Comment by fabiocarvalho777** [comment]
Cool, thank you very much!!

**Comment by badalsarkar** [comment]
Hi Fábio,
I have done some work. [This integration](https://github.com/paypal/butterfly/blob/104d32e6659269c830fdfd66bd02007e8ab8c770/extensions-catalog/butterfly-springboot-extension/src/test/java/com/paypal/butterfly/extensions/springboot/JavaEEToSpringBootIT.java#L38) test is failing. 

```bash
java.lang.AssertionError: Baseline and transformed applications don't match, the contents of one file differ, as detailed below:

	Baseline application:    /home/badal/Documents/codeProject/butterfly/extensions-catalog/butterfly-springboot-extension/../../tests/transformed-baseline/echo-JavaEEToSpringBoot
	Transformed application: /tmp/butterfly-test1456204905109237410/echo-transformed-20210114172136901-d72b05af-601e-4082-8325-3749225838a0


	File: 		/pom.xml
	At: 		line 1, column 15
	Expected: 	'"'
	Found: 		'''
	at com.paypal.butterfly.test.FoldersComparison.failSingleDifferentFile(FoldersComparison.java:91)
	at com.paypal.butterfly.test.FoldersComparison.assertEquals(FoldersComparison.java:56)
	at com.paypal.butterfly.test.Assert.assertTransformation(Assert.java:149)
	at com.paypal.butterfly.test.Assert.assertTransformation(Assert.java:104)
	at com.paypal.butterfly.extensions.springboot.JavaEEToSpringBootIT.sampleAppRunTest(JavaEEToSpringBootIT.java:46)
```

Expected output is like
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
```

but the actual output is like
```xml
<?xml version='1.0' encoding='UTF-8'?><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
```
This, I believe it is not related to my code. StAX is reading `<?xml version="1.0" encoding="UTF-8"?>` but writting 
`<?xml version='1.0' encoding='UTF-8'?>`. Also it is ignoring the `\n` at the end of `DocumentStart` element. I not sure if it is related to my system. I am still investigating. 

Would you please take a look at the code? Or let me know if there is something I am missing.

I still need to add some tests and check the code.

Thanks. :smile:

**Comment by fabiocarvalho777** [comment]
Hello Badal,

I took a look at your changes and I don't see any problem with it.
Also, [we can see here](https://github.com/paypal/butterfly/blob/develop/extensions-catalog/butterfly-springboot-extension/src/main/java/com/paypal/butterfly/extensions/springboot/JavaEEToSpringBoot.java#L49-L50) that `PomAddDependency`, the TO you are modifying as part of this issue, is being used in the transformation template used in that test. Having said that, I think it is just natural that the format of the top of the XML file would change. By the way, notice this difference is harmless. They are conceptually the same, but written differently. It is just a matter of preference between the Maven library we used to modify pom files in a DOM manner, versus StAX.

Having said that, please go ahead and change the baseline XML test file to match what StAX is producing, and the test should pass.

I hope this clarifies your questions. Let me know if not, or if you have other questions.

Thank you very much for working on this issue!

**Comment by badalsarkar** [comment]
Yes, this is clear to me. Working on it. :smile:
